version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./config/my.cnf:/etc/mysql/my.cnf
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wp
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: $USER_PASSWD_MYSQL

  wordpress:
    depends_on:
      - db
    image: wordpress:4.9.4
    volumes:
      - ./wordpress_data:/var/www/
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: $USER_PASSWD_MYSQL
      WORDPRESS_DB_NAME: wp
